### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by jsam** [mon4ter/sanic-jsonrpc#10]
Hello,

Your project looks really interesting and we are checking it out to use it on our next project. However, first thing we noticed is that it doesn't support Python 3.9. Is there any plans on adding that support, expanding the documentation and potentially add more features to it in the future?

Thanks!

**Comment by mon4ter** [comment]
Hello @jsam,

Thank you for your interest in the project, I appreciate it!
Support of Python 3.9 and 3.10 are definantly will be added soon. Actually, I'm going to look into it right away as I noticed your need for it.
I know about the lack of documentation. Unfortunately, the only way you can see how to use all the features is read the tests. I would love to have a documentation for the project, but I don't have any experience in creating automated documentation yet. PRs are welcome!
If you have any feature requests I'd love to hear them!

Stay tuned for Python 3.9 and 3.10 support!

**Comment by mon4ter** [comment]
@jsam Python 3.9 support has added with #11, release 0.3.2 is out. Actually, it's added by [fashionable](/mon4ter/fashionable)'s release 0.11.1, make sure you've updated it too. Notice that Sanic 21.3 is not supported because [pytest-sanic](/yunstanford/pytest-sanic) has no support for Sanic 21.3 yet ([#50](/yunstanford/pytest-sanic/issues/50) ).

**Comment by jsam** [comment]
Thank you so much. Really happy to see this project being alive.
